name: CI - Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps for backend
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-requirements.txt

      - name: Run backend health smoke test (in-process)
        run: |
          python - <<'PY'
          import os, sys
          sys.path.insert(0, os.path.abspath('backend'))
          import main as appmod
          from fastapi.testclient import TestClient
          c = TestClient(appmod.app)
          r = c.get('/')
          assert r.status_code == 200, r.text
          body = r.json()
          assert body.get('status') == 'ok', body
          print('Smoke OK:', body)
          PY
